### PR TITLE
Dockerfile updated to pass all the Red Hat Certification requirements

### PR DESCRIPTION
**Pull request by manojjahgirdar**
The Dockerfile now passes the following Tests on Red Hat Certification:
- [x] `is_rhel`
- [x] `has_licenses`
- [x] `rpm_list_successful`
- [x] `not_running_privileged`
- [x] `not_running_as_root`
- [x] `name_label_exists`
- [x] `vendor_label_exists`
- [x] `version_label_exists`
- [x] `release_label_exists`
- [x] `good_tags`
- [x] `good_layer_count`
- [x] `free_of_critical_vulnerabilities`
- [x] `free_of_important_vulnerabilities`
- [x] `non_inherited_base_label_name`
- [x] `non_inherited_base_label_vendor`
- [x] `non_inherited_base_label_description`
- [x] `non_inherited_base_label_summary`
- [x] `has_base_rh_image`
- [x] `ubi_content_ok`
- [x] `has_under_40_layers`

The test `free_of_critical_vulnerabilities` is failing because `ubi8/openjdk-11:1.3-11` still contains a [known vulnerability](https://catalog.redhat.com/software/containers/ubi8/openjdk-11/5dd6a4b45a13461646f677f4?gti-tabs=unauthenticated&container-tabs=security).

### CODE REVIEW

**Comment by bwoolf1** [comment]
Manoj: Good work. It looks like you've now switched the base image to ubi8/openjdk-8:1.3-9.1617297653, which doesn't contain any known security vulnerabilities. Does it now pass all certification checks?

You had to uncomment `RUN dnf -y update-minimal --security ...`. Now that the base image doesn't have vulnerabilities, if you comment it out again, does certification still pass?

`USER default` doesn't work, so you changed it to `USER 1001`. Good idea, but seems like `USER default` is supposed to work (when building from a UBI). If `default` won't work, I wonder if user 1001 will be an issue for deploying to Kubernetes. What default non-root user ID is best for Kubernetes? (OpenShift just ignores it.)

Moving the starter kit's license file into `./licenses` is a good plan. Then others can add additional licenses to that directory as needed.

**Comment by manojjahgirdar** [comment]
Bobby: The `free_of_critical_vulnerabilities` test still fails for ubi8/openjdk-8:1.3-9.1617297653. 

Yes if I comment `RUN dnf -y update-minimal --security ...` the test for `free_of_important_vulnerabilities` still passes.

The `USER` default is throwing an error because `FROM quay.io/ibmgaragecloud/gradle:jdk11 AS builder` this builder image has no user called `default` in the passwd file.

**Comment by manojjahgirdar** [comment]
This Dockerfile now passes all the Red Hat Certification requirements.
Screenshot 2021-04-28 at 11 10 40 AM

**Comment by bwoolf1** [comment]
Manoj: I think this Dockerfile (https://github.com/IBM/template-java-spring/pull/11/commits/da611ff37f46f4ba17b99410c21c95e8d85b3c86) looks very good, and all the certification tests pass! Nice job!

I didn't realize this template doesn't have a license file. Thanks for adding one.

**Comment by bwoolf1** [comment]
LGTM. Nice job.

@csantanapr:
- Do you want the security update command commented out or not commented out by default?
- What do you think of the default values for version and release being the same as those for the UBI the image is built from?

**Comment by csantanapr** [comment]
@bwoolf1 

I think is ok to leave the update uncommented 

Labels are ok as place holders, user will eventually customize 

I assume the app still works and toolkit pipelines doesn't has issues like a timeout

**Comment by csantanapr** [comment]
On today's sprint meeting to leave yum update line commented out
cc @bwoolf1 @seansund

**Comment by bwoolf1** [comment]
@csantanapr: What updates do you want to this PR to approve it? As you said above, comment out the security update. What else? Seems like you mentioned some other concerns. We need to document what you're looking for to pass these requests on to @manojjahgirdar. Thanks.

**Comment by manojjahgirdar** [comment]
- I have commented the updating image security content command.
- Here is a confirmation that the Dockerfile builds successfully after the improvements:
Screenshot 2021-05-05 at 12 39 21 PM

**Comment by csantanapr** [comment]
Please verify app still works on OpenShift, use the Toolkit pipeline to build and deploy

**Comment by manojjahgirdar** [comment]
> Please verify app still works on OpenShift, use the Toolkit pipeline to build and deploy

@csantanapr,
This passes all the tests except for the `gitops` one. The logs says the following:
```
unable to find result referenced by param "helm-url" in "gitops": Could not find result with name helm-url for task run helm-release
```
Screenshot 2021-05-05 at 8 47 13 PM

What does this mean?

**Comment by bwoolf1** [comment]
@manojjahgirdar: Remember to comment out the security update line.

**Comment by bwoolf1** [comment]
@manojjahgirdar: I'm not sure why your pipelines are failing on the `gitops` task. It's working for me.

I ran the pipeline using the current IBM/template-java-spring template and again with your changes. Both pipeline runs completed successfully for me. So I'm not sure what's the problem you're running into. 

The good news is that your new Dockerfile works (or at least doesn't break the pipeline). Also, upgrading to the new UBI has fixed all of the issues Vulnerability Advisor found in the old version. If we submitted v0.0.2 for certification, it should pass like your test images have.

The bad news: I don't know why your pipelines are failing. My best suggestion is to repeat the steps I've done (explained below) and see if that works for you too. (Maybe you have an old version of the template and this will fix it?)

-----

You can see my two pipeline runs that succeeded in my `dev-bw` project:
- `template-java-spring-20210505-1793dd84e00` is the Java  template unmodified
- `template-java-spring-20210505-5cfhk` is the file changes in this PR (the Dockerfile and the licenses dir)

You can also see two new images in the [ICCR](https://cloud.ibm.com/registry/images):
- isv-scenarios/template-java-spring-20210505:0.0.1, which has 39 issues
- isv-scenarios/template-java-spring-20210505:0.0.2, which has no issues

-----

Here's what I did that worked for me:
- I followed the process in [Deploying an App](https://cloudnativetoolkit.dev/getting-started-day-1/deploy-app)
- I forked https://github.com/IBM/template-java-spring into https://github.com/bwoolf1/template-java-spring-20210505
- I created the pipeline:
```
$ (isv-scenarios-ocp:dev-bw)➜  ~ oc pipeline https://github.com/bwoolf1/template-java-spring-20210505
? Select the type of pipeline that should be run? Tekton
Creating pipeline on openshift cluster in dev-bw namespace
Retrieving git parameters
Git credentials have already been stored for user: bwoolf1
  Project git repo: https://github.com/bwoolf1/template-java-spring-20210505.git
  Branch: master
Retrieving available template pipelines from tools
Pipeline templates filtered based on detected runtime: openjdk/gradle
Selected pipeline: ibm-java-gradle
? scan-image: Enable the pipeline to scan the image for vulnerabilities? No
Copying tasks from tools
Copied Pipeline from tools/ibm-java-gradle to dev-bw/template-java-spring-20210505
Creating TriggerTemplate for pipeline: template-java-spring-20210505
Creating TriggerBinding for pipeline: template-java-spring-20210505
Creating/updating TriggerEventListener for pipeline: tekton
  Waiting for event listener rollout: dev-bw/el-tekton
Creating/updating Route for pipeline: tekton
Creating PipelineRun for pipeline: template-java-spring-20210505
Creating Github webhook for repo: https://github.com/bwoolf1/template-java-spring-20210505.git

Pipeline run started: template-java-spring-20210505-1793dd84e00

Next steps:
  Tekton cli:
    View PipelineRun info - tkn pr describe template-java-spring-20210505-1793dd84e00
    View PipelineRun logs - tkn pr logs -f template-java-spring-20210505-1793dd84e00
  OpenShift console:
    View PipelineRun - https://console-openshift-console.isv-scenarios-ocp-f2c6cdc6801be85fd188b09d006f13e3-0000.us-south.containers.appdomain.cloud/k8s/ns/dev-bw/tekton.dev~v1beta1~PipelineRun/template-java-spring-20210505-1793dd84e00
```
Notice that it started pipeline run `template-java-spring-20210505-1793dd84e00`. You can see it in my project, it succeeded.
- I cloned my repo and copied the changes from this PR into my local copy. You can see those in my repo.
- When I pushed my changes to my server copy, the trigger started pipeline run `template-java-spring-20210505-5cfhk`. Again, you can see it in my project, it succeeded.

**Comment by manojjahgirdar** [comment]
(@bwoolf1) Bobby, Thank you for the detailed guide. I followed the same and ended up at the same `gitops` task failure. 

However, after spending a good amount of time reading the [Deploying an App](https://cloudnativetoolkit.dev/getting-started-day-1/deploy-app) documentation, I realised that Artifactory needs to be set up in order for the pipeline to work. This is nowhere mentioned in the [Deploying an App](https://cloudnativetoolkit.dev/getting-started-day-1/deploy-app) (Nor in the video). However, there is a mention about the [7. View your application artifacts](https://cloudnativetoolkit.dev/getting-started-day-1/deploy-app/#7.-view-your-application-artifacts) at the very end of the document. In this step, the documentation talks about the [artifact repository](https://cloudnativetoolkit.dev/tools/artifactory). Digging deep into the [artifact repository](https://cloudnativetoolkit.dev/tools/artifactory) documentation, it talks about [set up Artifactory](https://cloudnativetoolkit.dev/admin/artifactory-setup/) being a prerequisite for the development tools. 

Just to get the pre-requisites in place, this is too many redirects for a developer new to the Cloud Native Toolkit (like me) trying to Deploy an App through the pipeline by referring to the [Deploying an App](https://cloudnativetoolkit.dev/getting-started-day-1/deploy-app) documentation. I followed the [set up Artifactory](https://cloudnativetoolkit.dev/admin/artifactory-setup/)  document and was able to [Obtain the encrypted password](https://cloudnativetoolkit.dev/admin/artifactory-setup/#obtain-the-encrypted-password) and updated the `artifactory-access` secret  in the `tools` namespace as specified in the [Update the secret - OpenShift 4](https://cloudnativetoolkit.dev/admin/artifactory-setup/#update-the-secret-openshift-4) documentation.

I re-ran the pipeline as I had set up the Artifactory now. To my surprise, the pipeline still failed at `gitops` task. After comparing my project `dev-mj` with your project `dev-bw` to see where possibly I could have gone wrong, I noticed the `artifactory-access` secret was present in your project as well, I copied the `artifactory-access` secret from `tools` namespace to my namespace and finally the `gitops` task passed!

UPDATE: Somehow I had missed `oc sync dev-mj`, this step copies ConfigMaps and Secrets from `tools` namespace to my namespace. Thanks Bobby for bringing this up.

Thanks.

FYI @csantanapr.

**Comment by manojjahgirdar** [comment]
> Please verify app still works on OpenShift, use the Toolkit pipeline to build and deploy

@csantanapr, Here is the verification that the app still works on OpenShift, using the Toolkit pipeline to build and deploy.
Screenshot 2021-05-06 at 10 45 36 PM

**Comment by bwoolf1** [comment]
@manojjahgirdar: Glad you figured out the problem. I saw that your pipeline couldn't access Artifactory but didn't know why. I assumed because I could, Artifactory was working again, so you'd be OK. I didn't think to check in your project to see what secrets it had.

You didn't need to change the Artifactory password. Those steps probably changed it to what it already was, or everyone's pipelines would start having the problem yours had. What fixed it for you was when you copied the `artifactory-access` secret from `tools` namespace to your namespace. That gives your pipelines the credentials they need to use Artifactory.

How did you create your project? Sounds like you didn't do [2. Create the development namespace](https://cloudnativetoolkit.dev/getting-started-day-1/deploy-app#2.-create-the-development-namespace), which runs `oc sync ${DEV_NAMESPACE}`. Like the doc says, that copies the config and credentials from the `tools` namespace to your namespace. This may not be required in Kubernetes but it is in OpenShift because it treats every project as separate and runs each user's pipelines in their project. You should run that command on both of your projects to make sure they've got the stuff they need from `tools`, not just the Artifactory credentials.

**Comment by manojjahgirdar** [comment]
@csantanapr Vulnerability Advisor now finds no issues, here is proof.
Screenshot 2021-05-07 at 7 36 05 PM

**Review by csantanapr — APPROVED** [review]
LGTM

**Comment by csantanapr** [comment]
Thank you @manojjahgirdar for the contribution 👍

**Pull request merged**
