### PR TITLE
Copy licenses as non-root

### PR DESCRIPTION
**Pull request by bwoolf1**
Update the Dockerfile so that the licenses directory is copied as the non-root user.

### CODE REVIEW

**Comment by bwoolf1** [comment]
Step 6 switches to the non-root user and Step 7 copies the `licenses` directory.

image

**Comment by bwoolf1** [comment]
The pipeline completes successfully.

image

**Comment by bwoolf1** [comment]
The app in the container is running.

image

**Comment by bwoolf1** [comment]
Vulnerability Advisor found no issues in the image.

image

**Comment by bwoolf1** [comment]
Step 6 switches to the non-root user and Step 7 copies the `licenses` directory.

image

**Comment by bwoolf1** [comment]
The container has a `/licenses` directory that contains a `LICENSE.txt` file, both owned by user:group `1001:root`.

image

**Review by csantanapr — APPROVED** [review]
Thanks for the contribution @bwoolf1 
LGTM

**Pull request merged**
